### ISSUE TITLE
Práctica de Seguimiento y Control_METZTLI

### ISSUE THREAD

**Issue by Ferch0419** [SistemasTecTlaxiaco/actividad-9-practica-de-seguimiento-y-control-de-proyecto-entrevista-metztli_team#1]
[Práctica Seguimiento y Control METZTLI.pdf](https://github.com/SistemasTecTlaxiaco/actividad-9-practica-de-seguimiento-y-control-de-proyecto-entrevista-metztli_team/files/10192506/Practica.Seguimiento.y.Control.METZTLI.pdf)

**Comment by AndreLuna6** [comment]
Calificado 50%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
